/**
 * Curated Material Symbols icon options for the Features block.
 * Values are the icon identifiers used with the `material-symbols-outlined` CSS class.
 * Browse the full set at: https://fonts.google.com/icons
 * Note: All icons verified against material-symbols@0.42.3
 */

export const featureIconOptions: { title: string; value: string }[] = [
  { title: 'Accessibility', value: 'accessible' },
  { title: 'Anchor', value: 'anchor' },
  { title: 'Bakery', value: 'bakery_dining' },
  { title: 'Beach Umbrella', value: 'beach_access' },
  { title: 'Bicycle', value: 'directions_bike' },
  { title: 'Boat / Ferry', value: 'directions_boat' },
  { title: 'Bus', value: 'directions_bus' },
  { title: 'Calendar', value: 'event' },
  { title: 'Camera', value: 'photo_camera' },
  { title: 'Camping Tent', value: 'camping' },
  { title: 'Check Circle', value: 'check_circle' },
  { title: 'Church', value: 'church' },
  { title: 'Coffee', value: 'coffee' },
  { title: 'Cottage / Hut', value: 'cottage' },
  { title: 'Diamond', value: 'diamond' },
  { title: 'Eco Leaf', value: 'eco' },
  { title: 'Eye / Viewpoint', value: 'visibility' },
  { title: 'Family Home', value: 'family_home' },
  { title: 'Festival / Party', value: 'celebration' },
  { title: 'First Aid', value: 'medical_services' },
  { title: 'Flight / Airplane', value: 'flight' },
  { title: 'Food / Burger', value: 'lunch_dining' },
  { title: 'Forest / Trees', value: 'forest' },
  { title: 'Globe / Explore', value: 'travel_explore' },
  { title: 'Group / People', value: 'group' },
  { title: 'Gym / Dumbbell', value: 'fitness_center' },
  { title: 'Hiking', value: 'hiking' },
  { title: 'Hotel Bed', value: 'bed' },
  { title: 'Info', value: 'info' },
  { title: 'Kayaking', value: 'kayaking' },
  { title: 'Lightbulb', value: 'lightbulb' },
  { title: 'Liquor / Cocktail Glass', value: 'local_bar' },
  { title: 'Location Pin', value: 'location_on' },
  { title: 'Luggage', value: 'luggage' },
  { title: 'Map', value: 'map' },
  { title: 'Medal', value: 'military_tech' },
  { title: 'Mountain / Landscape', value: 'landscape' },
  { title: 'Motorcycle / Scooter', value: 'two_wheeler' },
  { title: 'Museum', value: 'museum' },
  { title: 'Music Note', value: 'music_note' },
  { title: 'Navigation Arrow', value: 'navigation' },
  { title: 'Nightlife / Cocktail', value: 'nightlife' },
  { title: 'No Animal Harm / Eco', value: 'cruelty_free' },
  { title: 'Park / Tree', value: 'park' },
  { title: 'Paragliding', value: 'paragliding' },
  { title: 'Person / Guide', value: 'person' },
  { title: 'Person + Nature', value: 'nature_people' },
  { title: 'Restaurant / Cutlery', value: 'restaurant' },
  { title: 'Route / Path', value: 'route' },
  { title: 'Rowing', value: 'rowing' },
  { title: 'Running', value: 'directions_run' },
  { title: 'Safety Shield', value: 'health_and_safety' },
  { title: 'Sailboat', value: 'sailing' },
  { title: 'Schedule / Clock', value: 'schedule' },
  { title: 'Scuba Diving', value: 'scuba_diving' },
  { title: 'Seafood / Meal Set', value: 'set_meal' },
  { title: 'Spa Flower', value: 'spa' },
  { title: 'Sports Ball', value: 'sports' },
  { title: 'Star', value: 'star' },
  { title: 'Support / Headset', value: 'support_agent' },
  { title: 'Surfing', value: 'surfing' },
  { title: 'Swimming / Pool', value: 'pool' },
  { title: 'Tree / Nature', value: 'nature' },
  { title: 'Verified Badge', value: 'verified' },
  { title: 'Water / Ocean', value: 'water' },
  { title: 'Water Drop', value: 'water_drop' },
  { title: 'Waves', value: 'waves' },
  { title: 'Wifi', value: 'wifi' },
]
