/**
 * Curated Material Symbols icon options for use across all icon picker fields.
 * Values are the icon identifiers used with the `material-symbols-outlined` CSS class.
 * Browse the full set at: https://fonts.google.com/icons
 * All icons verified against material-symbols@0.42.3
 */

export type IconOption = {
  title: string
  value: string
  category: string
}

export const ICON_OPTIONS: IconOption[] = [
  // Navigation & Transport
  { title: 'Bus', value: 'directions_bus', category: 'Navigation & Transport' },
  { title: 'Car / Drive', value: 'directions_car', category: 'Navigation & Transport' },
  { title: 'Bicycle', value: 'directions_bike', category: 'Navigation & Transport' },
  { title: 'Boat / Ferry', value: 'directions_boat', category: 'Navigation & Transport' },
  { title: 'Flight / Airplane', value: 'flight', category: 'Navigation & Transport' },
  { title: 'Motorcycle / Scooter', value: 'two_wheeler', category: 'Navigation & Transport' },
  { title: 'Running', value: 'directions_run', category: 'Navigation & Transport' },
  { title: 'Walking', value: 'directions_walk', category: 'Navigation & Transport' },
  { title: 'Train', value: 'train', category: 'Navigation & Transport' },
  { title: 'Subway', value: 'subway', category: 'Navigation & Transport' },
  { title: 'Taxi', value: 'local_taxi', category: 'Navigation & Transport' },
  { title: 'Route / Path', value: 'route', category: 'Navigation & Transport' },
  { title: 'Map', value: 'map', category: 'Navigation & Transport' },
  { title: 'Navigation Arrow', value: 'navigation', category: 'Navigation & Transport' },
  { title: 'Location Pin', value: 'location_on', category: 'Navigation & Transport' },
  { title: 'Compass', value: 'explore', category: 'Navigation & Transport' },
  { title: 'Globe / World', value: 'language', category: 'Navigation & Transport' },
  { title: 'Globe / Explore', value: 'travel_explore', category: 'Navigation & Transport' },
  { title: 'Luggage', value: 'luggage', category: 'Navigation & Transport' },
  { title: 'Backpack', value: 'backpack', category: 'Navigation & Transport' },

  // Nature & Outdoors
  { title: 'Beach Umbrella', value: 'beach_access', category: 'Nature & Outdoors' },
  { title: 'Forest / Trees', value: 'forest', category: 'Nature & Outdoors' },
  { title: 'Tree / Nature', value: 'nature', category: 'Nature & Outdoors' },
  { title: 'Park / Tree', value: 'park', category: 'Nature & Outdoors' },
  { title: 'Mountain / Landscape', value: 'landscape', category: 'Nature & Outdoors' },
  { title: 'Waves', value: 'waves', category: 'Nature & Outdoors' },
  { title: 'Water / Ocean', value: 'water', category: 'Nature & Outdoors' },
  { title: 'Water Drop', value: 'water_drop', category: 'Nature & Outdoors' },
  { title: 'Eco Leaf', value: 'eco', category: 'Nature & Outdoors' },
  { title: 'No Animal Harm', value: 'cruelty_free', category: 'Nature & Outdoors' },
  { title: 'Sun / Sunny', value: 'wb_sunny', category: 'Nature & Outdoors' },
  { title: 'Cloud', value: 'cloud', category: 'Nature & Outdoors' },
  { title: 'Rain / Rainy', value: 'umbrella', category: 'Nature & Outdoors' },
  { title: 'Wind', value: 'air', category: 'Nature & Outdoors' },
  { title: 'Fire / Flame', value: 'local_fire_department', category: 'Nature & Outdoors' },
  { title: 'Flower / Bloom', value: 'local_florist', category: 'Nature & Outdoors' },
  { title: 'Terrain', value: 'terrain', category: 'Nature & Outdoors' },
  { title: 'Camping Tent', value: 'camping', category: 'Nature & Outdoors' },
  { title: 'Person + Nature', value: 'nature_people', category: 'Nature & Outdoors' },
  { title: 'Anchor', value: 'anchor', category: 'Nature & Outdoors' },

  // Food & Dining
  { title: 'Restaurant / Cutlery', value: 'restaurant', category: 'Food & Dining' },
  { title: 'Coffee', value: 'coffee', category: 'Food & Dining' },
  { title: 'Bakery', value: 'bakery_dining', category: 'Food & Dining' },
  { title: 'Food / Burger', value: 'lunch_dining', category: 'Food & Dining' },
  { title: 'Seafood / Meal Set', value: 'set_meal', category: 'Food & Dining' },
  { title: 'Liquor / Cocktail Glass', value: 'local_bar', category: 'Food & Dining' },
  { title: 'Nightlife / Cocktail', value: 'nightlife', category: 'Food & Dining' },
  { title: 'Ice Cream', value: 'icecream', category: 'Food & Dining' },
  { title: 'Cake / Dessert', value: 'cake', category: 'Food & Dining' },
  { title: 'Wine / Winemaking', value: 'wine_bar', category: 'Food & Dining' },
  { title: 'Local Cafe', value: 'local_cafe', category: 'Food & Dining' },
  { title: 'Takeout / Bag', value: 'takeout_dining', category: 'Food & Dining' },
  { title: 'Pizza', value: 'local_pizza', category: 'Food & Dining' },
  { title: 'Kitchen / Blender', value: 'blender', category: 'Food & Dining' },
  { title: 'Grocery / Basket', value: 'local_grocery_store', category: 'Food & Dining' },

  // Activities & Sports
  { title: 'Hiking', value: 'hiking', category: 'Activities & Sports' },
  { title: 'Surfing', value: 'surfing', category: 'Activities & Sports' },
  { title: 'Kayaking', value: 'kayaking', category: 'Activities & Sports' },
  { title: 'Rowing', value: 'rowing', category: 'Activities & Sports' },
  { title: 'Sailing', value: 'sailing', category: 'Activities & Sports' },
  { title: 'Scuba Diving', value: 'scuba_diving', category: 'Activities & Sports' },
  { title: 'Swimming / Pool', value: 'pool', category: 'Activities & Sports' },
  { title: 'Sports Ball', value: 'sports', category: 'Activities & Sports' },
  { title: 'Gym / Dumbbell', value: 'fitness_center', category: 'Activities & Sports' },
  { title: 'Paragliding', value: 'paragliding', category: 'Activities & Sports' },
  { title: 'Yoga', value: 'self_improvement', category: 'Activities & Sports' },
  { title: 'Skiing', value: 'downhill_skiing', category: 'Activities & Sports' },
  { title: 'Cycling Race', value: 'pedal_bike', category: 'Activities & Sports' },
  { title: 'Golf', value: 'golf_course', category: 'Activities & Sports' },
  { title: 'Tennis', value: 'sports_tennis', category: 'Activities & Sports' },
  { title: 'Soccer / Football', value: 'sports_soccer', category: 'Activities & Sports' },
  { title: 'Basketball', value: 'sports_basketball', category: 'Activities & Sports' },
  { title: 'Baseball', value: 'sports_baseball', category: 'Activities & Sports' },
  { title: 'Volleyball', value: 'sports_volleyball', category: 'Activities & Sports' },
  { title: 'Fishing', value: 'phishing', category: 'Activities & Sports' },
  { title: 'Rock Climbing', value: 'climbing', category: 'Activities & Sports' },
  { title: 'Skateboarder', value: 'skateboarding', category: 'Activities & Sports' },

  // Culture & Attractions
  { title: 'Museum', value: 'museum', category: 'Culture & Attractions' },
  { title: 'Church', value: 'church', category: 'Culture & Attractions' },
  { title: 'Festival / Party', value: 'celebration', category: 'Culture & Attractions' },
  { title: 'Music Note', value: 'music_note', category: 'Culture & Attractions' },
  { title: 'Theater / Arts', value: 'theater_comedy', category: 'Culture & Attractions' },
  { title: 'Camera', value: 'photo_camera', category: 'Culture & Attractions' },
  { title: 'Gallery / Image', value: 'image', category: 'Culture & Attractions' },
  { title: 'Book / Read', value: 'menu_book', category: 'Culture & Attractions' },
  { title: 'Library', value: 'local_library', category: 'Culture & Attractions' },
  { title: 'Landmark', value: 'account_balance', category: 'Culture & Attractions' },
  { title: 'Calendar / Event', value: 'event', category: 'Culture & Attractions' },
  { title: 'Dance / Entertainment', value: 'sports_martial_arts', category: 'Culture & Attractions' },
  { title: 'Film / Cinema', value: 'movie', category: 'Culture & Attractions' },
  { title: 'Art Palette', value: 'palette', category: 'Culture & Attractions' },
  { title: 'Ticket', value: 'confirmation_number', category: 'Culture & Attractions' },
  { title: 'Trophy / Award', value: 'emoji_events', category: 'Culture & Attractions' },
  { title: 'Medal', value: 'military_tech', category: 'Culture & Attractions' },
  { title: 'Diamond', value: 'diamond', category: 'Culture & Attractions' },

  // Accommodation & Services
  { title: 'Hotel Bed', value: 'bed', category: 'Accommodation & Services' },
  { title: 'Cottage / Hut', value: 'cottage', category: 'Accommodation & Services' },
  { title: 'Family Home', value: 'family_home', category: 'Accommodation & Services' },
  { title: 'Apartment', value: 'apartment', category: 'Accommodation & Services' },
  { title: 'Spa Flower', value: 'spa', category: 'Accommodation & Services' },
  { title: 'Support / Headset', value: 'support_agent', category: 'Accommodation & Services' },
  { title: 'Wifi', value: 'wifi', category: 'Accommodation & Services' },
  { title: 'Accessibility', value: 'accessible', category: 'Accommodation & Services' },
  { title: 'Safety Shield', value: 'health_and_safety', category: 'Accommodation & Services' },
  { title: 'First Aid', value: 'medical_services', category: 'Accommodation & Services' },
  { title: 'Parking', value: 'local_parking', category: 'Accommodation & Services' },
  { title: 'Pool (Hotel)', value: 'pool', category: 'Accommodation & Services' },
  { title: 'Concierge / Bell', value: 'room_service', category: 'Accommodation & Services' },
  { title: 'Key / Room', value: 'key', category: 'Accommodation & Services' },
  { title: 'Pet Friendly', value: 'pets', category: 'Accommodation & Services' },
  { title: 'Laundry', value: 'local_laundry_service', category: 'Accommodation & Services' },
  { title: 'Air Conditioning', value: 'ac_unit', category: 'Accommodation & Services' },
  { title: 'Balcony / Deck', value: 'deck', category: 'Accommodation & Services' },
  { title: 'Security', value: 'security', category: 'Accommodation & Services' },
  { title: 'Schedule / Clock', value: 'schedule', category: 'Accommodation & Services' },

  // General UI
  { title: 'Star', value: 'star', category: 'General UI' },
  { title: 'Check Circle', value: 'check_circle', category: 'General UI' },
  { title: 'Info', value: 'info', category: 'General UI' },
  { title: 'Lightbulb', value: 'lightbulb', category: 'General UI' },
  { title: 'Verified Badge', value: 'verified', category: 'General UI' },
  { title: 'Group / People', value: 'group', category: 'General UI' },
  { title: 'Person / Guide', value: 'person', category: 'General UI' },
  { title: 'Phone', value: 'phone', category: 'General UI' },
  { title: 'Email', value: 'mail', category: 'General UI' },
  { title: 'Chat / Message', value: 'chat', category: 'General UI' },
  { title: 'Search', value: 'search', category: 'General UI' },
  { title: 'Settings', value: 'settings', category: 'General UI' },
  { title: 'Favorite / Heart', value: 'favorite', category: 'General UI' },
  { title: 'Bookmark', value: 'bookmark', category: 'General UI' },
  { title: 'Share', value: 'share', category: 'General UI' },
  { title: 'Arrow Forward', value: 'arrow_forward', category: 'General UI' },
  { title: 'Arrow Outward', value: 'arrow_outward', category: 'General UI' },
  { title: 'Open In New', value: 'open_in_new', category: 'General UI' },
  { title: 'Download', value: 'download', category: 'General UI' },
  { title: 'Upload', value: 'upload', category: 'General UI' },
  { title: 'Warning', value: 'warning', category: 'General UI' },
  { title: 'Error / Alert', value: 'error', category: 'General UI' },
  { title: 'Lock', value: 'lock', category: 'General UI' },
  { title: 'Eye / Viewpoint', value: 'visibility', category: 'General UI' },
  { title: 'Refresh / Update', value: 'refresh', category: 'General UI' },
  { title: 'Calendar', value: 'calendar_today', category: 'General UI' },
  { title: 'Clock', value: 'access_time', category: 'General UI' },
  { title: 'Tag / Label', value: 'label', category: 'General UI' },
  { title: 'Filter', value: 'filter_list', category: 'General UI' },
  { title: 'Sort', value: 'sort', category: 'General UI' },
]
